// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using UIKit;

namespace PersistentBottomSheet.Touch.Views
{
    public partial class SampleViewController : UIViewController//MvxTableViewController<SampleViewModel>
	{
		public SampleViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            SetupBottomSheet();
        }

        private void SetupBottomSheet()
        {
            // 1- Init bottomSheetVC
            var bottomSheetVC = new BottomSheetViewController();

            // 2- Add bottomSheetVC as a child view 
            this.AddChildViewController(bottomSheetVC);
            this.View.AddSubview(bottomSheetVC.View);
            bottomSheetVC.DidMoveToParentViewController(this);

            // 3- Adjust bottomSheet frame and initial position.
            var height = View.Frame.Height;
            var width = View.Frame.Width;
            bottomSheetVC.View.Frame = new CGRect(0, this.View.Frame.GetMaxY(), width, height);
        }
    }
}