// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Platforms.Ios.Presenters.Attributes;
using MvvmCross.Platforms.Ios.Views;
using PersistentBottomSheet.Core.ViewModels;
using PersistentBottomSheet.Touch.Components;
using UIKit;

namespace PersistentBottomSheet.Touch.Views
{
    [MvxRootPresentation]
    public partial class SampleViewController : UITableViewController//MvxTableViewController<SampleViewModel>
	{
		public SampleViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            SetupParallaxHeader();
    }


        //MARK: private

        private void SetupParallaxHeader()
        {
            var imageView = new UIImageView();
            imageView.Image = UIImage.FromFile("profile");
            //imageView.ContentMode = UIViewContentMode.ScaleToFill.ScaleAspectFill;



            //headerImageView = imageView
            bottomView.BottomHeader = new BottomSheetHeader();
            bottomView.BottomHeader.View = imageView;
            bottomView.BottomHeader.Height = 400;
            bottomView.BottomHeader.MinimumHeight = 0;
            bottomView.BottomHeader.Mode = BottomSheetHeaderMode.TopFill;
            //bottomView.BottomHeader.parallaxHeaderDidScrollHandler = {
            //    parallaxHeader in
            //print(parallaxHeader.progress)
        }



        //MARK: table view data source/delegate

        public override nint RowsInSection(UITableView tableView, nint section)
        {
            return 20;
        }

        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = new UITableViewCell();
            cell.TextLabel.Text = "blablabla";
            return cell;
        }
    }
}